### ISSUE TITLE
Connect to SQLPLUS binary is missing

### ISSUE THREAD

**Issue by craph** [asiandevs/OracleDBAwithAnsible#2]
Hi,

I write this issue because I'm enable to find the part : 6 :Validation - Connect to SQLPLUS binary

Is it a mistake ?

How can we check if Oracle Database installation is correct ?

Thank you very much.

Best regards,

**Comment by craph** [comment]
Hello,

Please could you give a feedback about this point ?

I would like to know how can I check if Oracle Database is correctly installed.

Is it possible to do the same like here : https://github.com/asiandevs/GI_19cSoftInstall/blob/master/ansible/roles/racdbsoft19c_install/tasks/racdbsoft19c_installvalidate.yml

**Comment by monowar-mukul** [comment]
Hi, I did not connect to github for a long time. Please let me know hat is happening?

Is there any "sqlplus " to your software install directory [ $ORACLE_HOME/bin ] ? 

Thanks,
Monowar

**Comment by monowar-mukul** [comment]
https://medium.com/oracledevs/devops-series-automate-oracle-19c-rdbms-installations-with-ansible-github-43cfdf344a4a

Check section: Validation of Managed Nodes
