### ISSUE TITLE
UI not opening after the installation

### ISSUE THREAD

**Issue by uadhikari1989** [asiandevs/OracleDBAwithAnsible#3]
My playbook worked as expected but the oracleDB UI didn't open. I have all the ports open. What I mean to say is for oracleDB 12.1.0.2 if we go to the browser and do https://x.x.x.x:5500/em the UI would open. But in this case what should be done.

I checked the code but couldn't see thi is defined anywhere.

![image](https://user-images.githubusercontent.com/42251216/87562129-388cfa00-c683-11ea-98e5-604bb931b88e.png)

**Comment by monowar-mukul** [comment]
Hi, I did not add em part in my script.
